import type { Metadata } from "next";
import {Devonshire, Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {Header} from "@/widgets/Header/ui/Header";
import {StoreProvider} from "@/app/StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const devon = Devonshire({
  variable: "--font-devon",
  subsets: ["latin"],
  weight: '400',
})

export const metadata: Metadata = {
  title: "Kin-to | Главная",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${devon.variable} antialiased`}
      >
      <StoreProvider>
        <main className="min-h-screen">
          <Header />
          {children}
        </main>
      </StoreProvider>
      </body>
    </html>
  );
}
